/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "app_config-template": () => import("@/views/app/config-template/index.vue"),
  app_definition: () => import("@/views/app/definition/index.vue"),
  app_package: () => import("@/views/app/package/index.vue"),
  "app_script-template": () => import("@/views/app/script-template/index.vue"),
  app_version: () => import("@/views/app/version/index.vue"),
  asset_credential: () => import("@/views/asset/credential/index.vue"),
  asset_database: () => import("@/views/asset/database/index.vue"),
  asset_group: () => import("@/views/asset/group/index.vue"),
  asset_host: () => import("@/views/asset/host/index.vue"),
  asset_tag: () => import("@/views/asset/tag/index.vue"),
  deploy_task: () => import("@/views/deploy/task/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "monitor_detect-task": () => import("@/views/monitor/detect-task/index.vue"),
  monitor_metric: () => import("@/views/monitor/metric/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
  task_center: () => import("@/views/task/center/index.vue"),
  traffic_controller: () => import("@/views/traffic/controller/index.vue"),
};
