/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'app',
    path: '/app',
    component: 'layout.base',
    meta: {
      title: 'app',
      i18nKey: 'route.app',
      icon: 'mdi:application-braces-outline',
      order: 4
    },
    children: [
      {
        name: 'app_config-template',
        path: '/app/config-template',
        component: 'view.app_config-template',
        meta: {
          title: 'app_config-template',
          i18nKey: 'route.app_config-template'
        }
      },
      {
        name: 'app_definition',
        path: '/app/definition',
        component: 'view.app_definition',
        meta: {
          title: 'app_definition',
          i18nKey: 'route.app_definition'
        }
      },
      {
        name: 'app_package',
        path: '/app/package',
        component: 'view.app_package',
        meta: {
          title: 'app_package',
          i18nKey: 'route.app_package'
        }
      },
      {
        name: 'app_script-template',
        path: '/app/script-template',
        component: 'view.app_script-template',
        meta: {
          title: 'app_script-template',
          i18nKey: 'route.app_script-template'
        }
      },
      {
        name: 'app_version',
        path: '/app/version',
        component: 'view.app_version',
        meta: {
          title: 'app_version',
          i18nKey: 'route.app_version'
        }
      }
    ]
  },
  {
    name: 'asset',
    path: '/asset',
    component: 'layout.base',
    meta: {
      title: 'asset',
      i18nKey: 'route.asset',
      icon: 'mdi:server-network',
      order: 2
    },
    children: [
      {
        name: 'asset_credential',
        path: '/asset/credential',
        component: 'view.asset_credential',
        meta: {
          title: 'asset_credential',
          i18nKey: 'route.asset_credential'
        }
      },
      {
        name: 'asset_database',
        path: '/asset/database',
        component: 'view.asset_database',
        meta: {
          title: 'asset_database',
          i18nKey: 'route.asset_database'
        }
      },
      {
        name: 'asset_group',
        path: '/asset/group',
        component: 'view.asset_group',
        meta: {
          title: 'asset_group',
          i18nKey: 'route.asset_group'
        }
      },
      {
        name: 'asset_host',
        path: '/asset/host',
        component: 'view.asset_host',
        meta: {
          title: 'asset_host',
          i18nKey: 'route.asset_host'
        }
      },
      {
        name: 'asset_tag',
        path: '/asset/tag',
        component: 'view.asset_tag',
        meta: {
          title: 'asset_tag',
          i18nKey: 'route.asset_tag'
        }
      }
    ]
  },
  {
    name: 'deploy',
    path: '/deploy',
    component: 'layout.base',
    meta: {
      title: 'deploy',
      i18nKey: 'route.deploy',
      icon: 'mdi:rocket-launch-outline',
      order: 5
    },
    children: [
      {
        name: 'deploy_task',
        path: '/deploy/task',
        component: 'view.deploy_task',
        meta: {
          title: 'deploy_task',
          i18nKey: 'route.deploy_task'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor',
      icon: 'mdi:radar',
      order: 3
    },
    children: [
      {
        name: 'monitor_detect-task',
        path: '/monitor/detect-task',
        component: 'view.monitor_detect-task',
        meta: {
          title: 'monitor_detect-task',
          i18nKey: 'route.monitor_detect-task'
        }
      },
      {
        name: 'monitor_metric',
        path: '/monitor/metric',
        component: 'view.monitor_metric',
        meta: {
          title: 'monitor_metric',
          i18nKey: 'route.monitor_metric'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'mdi:account-cog-outline',
      order: 8
    },
    children: [
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      },
      {
        name: 'system_rbac',
        path: '/system/rbac',
        component: 'view.system_rbac',
        meta: {
          title: 'system_rbac',
          i18nKey: 'route.system_rbac'
        }
      }
    ]
  },
  {
    name: 'task',
    path: '/task',
    component: 'layout.base',
    meta: {
      title: 'task',
      i18nKey: 'route.task',
      icon: 'mdi:clipboard-text-clock-outline',
      order: 6
    },
    children: [
      {
        name: 'task_center',
        path: '/task/center',
        component: 'view.task_center',
        meta: {
          title: 'task_center',
          i18nKey: 'route.task_center'
        }
      },
      {
        name: 'task_tracking_[id]',
        path: '/task/tracking/:id',
        component: 'view.task_tracking_[id]',
        meta: {
          title: 'task_tracking_[id]'
        }
      }
    ]
  },
  {
    name: 'traffic',
    path: '/traffic',
    component: 'layout.base',
    meta: {
      title: 'traffic',
      i18nKey: 'route.traffic',
      icon: 'mdi:source-branch',
      order: 7
    },
    children: [
      {
        name: 'traffic_controller',
        path: '/traffic/controller',
        component: 'view.traffic_controller',
        meta: {
          title: 'traffic_controller',
          i18nKey: 'route.traffic_controller'
        }
      }
    ]
  }
];
